version: 2.1
jobs:
  build:  # This is the name of the job, feel free to change it to better match what you're trying to do!
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dep
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint